# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhufeng/zserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhufeng/zserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhufeng/zserver/CMakeFiles /home/zhufeng/zserver/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhufeng/zserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

zclient.o: zclient.cpp.o
.PHONY : zclient.o

# target to build an object file
zclient.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zclient.cpp.o
.PHONY : zclient.cpp.o

zclient.i: zclient.cpp.i
.PHONY : zclient.i

# target to preprocess a source file
zclient.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zclient.cpp.i
.PHONY : zclient.cpp.i

zclient.s: zclient.cpp.s
.PHONY : zclient.s

# target to generate assembly for a file
zclient.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zclient.cpp.s
.PHONY : zclient.cpp.s

zconfig.o: zconfig.cpp.o
.PHONY : zconfig.o

# target to build an object file
zconfig.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zconfig.cpp.o
.PHONY : zconfig.cpp.o

zconfig.i: zconfig.cpp.i
.PHONY : zconfig.i

# target to preprocess a source file
zconfig.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zconfig.cpp.i
.PHONY : zconfig.cpp.i

zconfig.s: zconfig.cpp.s
.PHONY : zconfig.s

# target to generate assembly for a file
zconfig.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zconfig.cpp.s
.PHONY : zconfig.cpp.s

zepoll.o: zepoll.cpp.o
.PHONY : zepoll.o

# target to build an object file
zepoll.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zepoll.cpp.o
.PHONY : zepoll.cpp.o

zepoll.i: zepoll.cpp.i
.PHONY : zepoll.i

# target to preprocess a source file
zepoll.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zepoll.cpp.i
.PHONY : zepoll.cpp.i

zepoll.s: zepoll.cpp.s
.PHONY : zepoll.s

# target to generate assembly for a file
zepoll.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zepoll.cpp.s
.PHONY : zepoll.cpp.s

zexample_module.o: zexample_module.cpp.o
.PHONY : zexample_module.o

# target to build an object file
zexample_module.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zexample_module.cpp.o
.PHONY : zexample_module.cpp.o

zexample_module.i: zexample_module.cpp.i
.PHONY : zexample_module.i

# target to preprocess a source file
zexample_module.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zexample_module.cpp.i
.PHONY : zexample_module.cpp.i

zexample_module.s: zexample_module.cpp.s
.PHONY : zexample_module.s

# target to generate assembly for a file
zexample_module.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zexample_module.cpp.s
.PHONY : zexample_module.cpp.s

zlog.o: zlog.cpp.o
.PHONY : zlog.o

# target to build an object file
zlog.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zlog.cpp.o
.PHONY : zlog.cpp.o

zlog.i: zlog.cpp.i
.PHONY : zlog.i

# target to preprocess a source file
zlog.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zlog.cpp.i
.PHONY : zlog.cpp.i

zlog.s: zlog.cpp.s
.PHONY : zlog.s

# target to generate assembly for a file
zlog.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zlog.cpp.s
.PHONY : zlog.cpp.s

zpacket.o: zpacket.cpp.o
.PHONY : zpacket.o

# target to build an object file
zpacket.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zpacket.cpp.o
.PHONY : zpacket.cpp.o

zpacket.i: zpacket.cpp.i
.PHONY : zpacket.i

# target to preprocess a source file
zpacket.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zpacket.cpp.i
.PHONY : zpacket.cpp.i

zpacket.s: zpacket.cpp.s
.PHONY : zpacket.s

# target to generate assembly for a file
zpacket.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zpacket.cpp.s
.PHONY : zpacket.cpp.s

zserver.o: zserver.cpp.o
.PHONY : zserver.o

# target to build an object file
zserver.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zserver.cpp.o
.PHONY : zserver.cpp.o

zserver.i: zserver.cpp.i
.PHONY : zserver.i

# target to preprocess a source file
zserver.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zserver.cpp.i
.PHONY : zserver.cpp.i

zserver.s: zserver.cpp.s
.PHONY : zserver.s

# target to generate assembly for a file
zserver.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zserver.cpp.s
.PHONY : zserver.cpp.s

zstream.o: zstream.cpp.o
.PHONY : zstream.o

# target to build an object file
zstream.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zstream.cpp.o
.PHONY : zstream.cpp.o

zstream.i: zstream.cpp.i
.PHONY : zstream.i

# target to preprocess a source file
zstream.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zstream.cpp.i
.PHONY : zstream.cpp.i

zstream.s: zstream.cpp.s
.PHONY : zstream.s

# target to generate assembly for a file
zstream.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zstream.cpp.s
.PHONY : zstream.cpp.s

zthread_module.o: zthread_module.cpp.o
.PHONY : zthread_module.o

# target to build an object file
zthread_module.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zthread_module.cpp.o
.PHONY : zthread_module.cpp.o

zthread_module.i: zthread_module.cpp.i
.PHONY : zthread_module.i

# target to preprocess a source file
zthread_module.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zthread_module.cpp.i
.PHONY : zthread_module.cpp.i

zthread_module.s: zthread_module.cpp.s
.PHONY : zthread_module.s

# target to generate assembly for a file
zthread_module.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zthread_module.cpp.s
.PHONY : zthread_module.cpp.s

zworld.o: zworld.cpp.o
.PHONY : zworld.o

# target to build an object file
zworld.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zworld.cpp.o
.PHONY : zworld.cpp.o

zworld.i: zworld.cpp.i
.PHONY : zworld.i

# target to preprocess a source file
zworld.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zworld.cpp.i
.PHONY : zworld.cpp.i

zworld.s: zworld.cpp.s
.PHONY : zworld.s

# target to generate assembly for a file
zworld.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/zworld.cpp.s
.PHONY : zworld.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... zclient.o"
	@echo "... zclient.i"
	@echo "... zclient.s"
	@echo "... zconfig.o"
	@echo "... zconfig.i"
	@echo "... zconfig.s"
	@echo "... zepoll.o"
	@echo "... zepoll.i"
	@echo "... zepoll.s"
	@echo "... zexample_module.o"
	@echo "... zexample_module.i"
	@echo "... zexample_module.s"
	@echo "... zlog.o"
	@echo "... zlog.i"
	@echo "... zlog.s"
	@echo "... zpacket.o"
	@echo "... zpacket.i"
	@echo "... zpacket.s"
	@echo "... zserver.o"
	@echo "... zserver.i"
	@echo "... zserver.s"
	@echo "... zstream.o"
	@echo "... zstream.i"
	@echo "... zstream.s"
	@echo "... zthread_module.o"
	@echo "... zthread_module.i"
	@echo "... zthread_module.s"
	@echo "... zworld.o"
	@echo "... zworld.i"
	@echo "... zworld.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

